-- SQL PARA CONFIGURAR O SUPABASE
-- Copie e cole este código no 'SQL Editor' do seu painel do Supabase

-- 1. Tabela de Perfis
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    role TEXT DEFAULT 'agent',
    badge_text TEXT,
    badge_color TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabela de Memes
CREATE TABLE IF NOT EXISTS public.memes (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    title TEXT NOT NULL,
    author TEXT NOT NULL,
    posted_by TEXT NOT NULL,
    posted_by_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    file_url TEXT NOT NULL,
    file_type TEXT CHECK (file_type IN ('image', 'video', 'audio')),
    tags TEXT[] DEFAULT '{}',
    description TEXT,
    score INTEGER DEFAULT 0,
    views INTEGER DEFAULT 0,
    reports INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Tabela de Votos
CREATE TABLE IF NOT EXISTS public.votes (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
    meme_id UUID REFERENCES public.memes(id) ON DELETE CASCADE NOT NULL,
    value INTEGER CHECK (value IN (1, -1)),
    UNIQUE(user_id, meme_id)
);

-- 4. Tabela de Denúncias
CREATE TABLE IF NOT EXISTS public.reports (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    meme_id UUID REFERENCES public.memes(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
    reason TEXT NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'resolved')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Tabela de Regras de Recompensa (Títulos)
CREATE TABLE IF NOT EXISTS public.reward_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric TEXT NOT NULL,
    operator TEXT NOT NULL,
    value NUMERIC NOT NULL,
    title_text TEXT NOT NULL,
    title_color TEXT DEFAULT '#22c55e',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Função para incrementar visualizações
CREATE OR REPLACE FUNCTION increment_meme_views(meme_id UUID)
RETURNS void AS $$
BEGIN
    UPDATE public.memes
    SET views = views + 1
    WHERE id = meme_id;
END;
$$ LANGUAGE plpgsql;

-- Trigger para atualizar contagem de score quando um voto é inserido/deletado/atualizado
-- (Opcional, mas melhora performance)
CREATE OR REPLACE FUNCTION update_meme_score()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'DELETE') THEN
        UPDATE public.memes SET score = (SELECT COALESCE(SUM(value), 0) FROM public.votes WHERE meme_id = OLD.meme_id) WHERE id = OLD.meme_id;
    ELSE
        UPDATE public.memes SET score = (SELECT COALESCE(SUM(value), 0) FROM public.votes WHERE meme_id = NEW.meme_id) WHERE id = NEW.meme_id;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_vote_change
AFTER INSERT OR UPDATE OR DELETE ON public.votes
FOR EACH ROW EXECUTE FUNCTION update_meme_score();

-- Políticas de Segurança (RLS) - Exemplo simples
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.memes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reward_rules ENABLE ROW LEVEL SECURITY;

-- Permissões de Leitura para todos
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Public memes are viewable by everyone" ON public.memes FOR SELECT USING (true);
CREATE POLICY "Public reward rules are viewable by everyone" ON public.reward_rules FOR SELECT USING (true);

-- Permissões de Escrita
CREATE POLICY "Users can insert their own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Authorized users can insert memes" ON public.memes FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Authors can delete their own memes" ON public.memes FOR DELETE USING (auth.uid() = posted_by_id);
CREATE POLICY "Authenticated users can vote" ON public.votes FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Authenticated users can report" ON public.reports FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- --- DICAS DE MIGRAÇÃO (Caso já tenha tabelas) ---
-- Se você receber erros de 'column not found', execute estes comandos para atualizar:
-- ALTER TABLE public.memes ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL;
-- ALTER TABLE public.memes ADD COLUMN IF NOT EXISTS posted_by_id UUID REFERENCES public.profiles(id);
-- ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS badge_text TEXT;
-- ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS badge_color TEXT;

-- --- COMANDO PARA SE TORNAR ADMIN ---
-- Substitua 'SEU_USERNAME' pelo seu nome de usuário após se cadastrar:
-- UPDATE public.profiles SET role = 'admin' WHERE username = 'SEU_USERNAME';
